export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN_LOADING = 'USER_LOADING';
export const USER_LOGIN_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOGIN_LOADING_FAIL = 'USER_LOADING_FAIL';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const GET_MOVIES_PHIM_LE_FETCHING='GET_MOVIES_PHIM_LE_FETCHING';
export const GET_MOVIES_PHIM_LE_SUCCESS='GET_MOVIES_PHIM_LE_SUCCESS';
export const GET_MOVIES_PHIM_LE_FAIL='GET_MOVIES_PHIM_LE_FAIL';

export const GET_MOVIES_PHIM_BO_FETCHING='GET_MOVIES_PHIM_BO_FETCHING';
export const GET_MOVIES_PHIM_BO_SUCCESS='GET_MOVIES_PHIM_BO_SUCCESS';
export const GET_MOVIES_PHIM_BO_FAIL='GET_MOVIES_PHIM_BO_FAIL';

export const GET_MOVIES_TV_SHOW_FETCHING='GET_MOVIES_TV_SHOW_FETCHING';
export const GET_MOVIES_TV_SHOW_SUCCESS='GET_MOVIES_TV_SHOW_SUCCESS';
export const GET_MOVIES_TV_SHOW_FAIL='GET_MOVIES_TV_SHOW_FAIL';

export const GET_TOP_MOVIE_FETCHING = 'GET_TOP_MOVIE_FETCHING';
export const GET_TOP_MOVIE_SUCCESS = 'GET_TOP_MOVIE_SUCCESS';
export const GET_TOP_MOVIE_FAIL = 'GET_TOP_MOVIE_FAIL';

export const GET_DETAIL_MOVIE_FETCHING = 'GET_DETAIL_MOVIE_FETCHING';
export const GET_DETAIL_MOVIE_SUCCESS = 'GET_DETAIL_MOVIE_SUCCESS';
export const GET_DETAIL_MOVIE_FAIL = 'GET_DETAIL_MOVIE_FAIL';

export const GET_ALL_GENRES_FETCHING = 'GET_ALL_GENRES_FETCHING';
export const GET_ALL_GENRES_SUCCESS = 'GET_ALL_GENRES_SUCCESS';
export const GET_ALL_GENRES_FAIL = 'GET_ALL_GENRES_FAIL';

export const GET_RECOMMEND_MOVIES_FETCHING = 'GET_RECOMMEND_MOVIES_FETCHING';
export const GET_RECOMMEND_MOVIES_SUCCESS = 'GET_RECOMMEND_MOVIES_SUCCESS';
export const GET_RECOMMEND_MOVIES_FAIL = 'GET_RECOMMEND_MOVIES_FAIL';

export const RESET_STATE_MOVIES = 'RESET_STATE_MOVIES';


