# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TVSea' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 # Pods for TVSea
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
#pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end
